// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rljtfxhqouhbkziyjbpt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJsanRmeGhxb3VoYmt6aXlqYnB0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzNDM4OTgsImV4cCI6MjA2MDkxOTg5OH0.hR1MWzqPxlWfU4eW1vLmxx4H3oKdrWLn_fTNzXlqAkk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);